// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: loan_payment_calculator.proto

package loan_payment_calculator_v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PaymentTiming int32

const (
	PaymentTiming_PAYMENT_TIMING_UNSPECIFIED         PaymentTiming = 0
	PaymentTiming_PAYMENT_TIMING_END_OF_PERIOD       PaymentTiming = 1
	PaymentTiming_PAYMENT_TIMING_BEGINNING_OF_PERIOD PaymentTiming = 2
)

// Enum value maps for PaymentTiming.
var (
	PaymentTiming_name = map[int32]string{
		0: "PAYMENT_TIMING_UNSPECIFIED",
		1: "PAYMENT_TIMING_END_OF_PERIOD",
		2: "PAYMENT_TIMING_BEGINNING_OF_PERIOD",
	}
	PaymentTiming_value = map[string]int32{
		"PAYMENT_TIMING_UNSPECIFIED":         0,
		"PAYMENT_TIMING_END_OF_PERIOD":       1,
		"PAYMENT_TIMING_BEGINNING_OF_PERIOD": 2,
	}
)

func (x PaymentTiming) Enum() *PaymentTiming {
	p := new(PaymentTiming)
	*p = x
	return p
}

func (x PaymentTiming) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentTiming) Descriptor() protoreflect.EnumDescriptor {
	return file_loan_payment_calculator_proto_enumTypes[0].Descriptor()
}

func (PaymentTiming) Type() protoreflect.EnumType {
	return &file_loan_payment_calculator_proto_enumTypes[0]
}

func (x PaymentTiming) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentTiming.Descriptor instead.
func (PaymentTiming) EnumDescriptor() ([]byte, []int) {
	return file_loan_payment_calculator_proto_rawDescGZIP(), []int{0}
}

type CalculatePMTRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rate          *Decimal               `protobuf:"bytes,1,opt,name=rate,proto3" json:"rate,omitempty"`
	Nper          int32                  `protobuf:"varint,2,opt,name=nper,proto3" json:"nper,omitempty"`
	PresentValue  *Decimal               `protobuf:"bytes,3,opt,name=present_value,json=presentValue,proto3" json:"present_value,omitempty"`
	FutureValue   *Decimal               `protobuf:"bytes,4,opt,name=future_value,json=futureValue,proto3,oneof" json:"future_value,omitempty"`
	PaymentTiming *PaymentTiming         `protobuf:"varint,5,opt,name=payment_timing,json=paymentTiming,proto3,enum=loan_payment_calculator.v1.PaymentTiming,oneof" json:"payment_timing,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePMTRequest) Reset() {
	*x = CalculatePMTRequest{}
	mi := &file_loan_payment_calculator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePMTRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePMTRequest) ProtoMessage() {}

func (x *CalculatePMTRequest) ProtoReflect() protoreflect.Message {
	mi := &file_loan_payment_calculator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePMTRequest.ProtoReflect.Descriptor instead.
func (*CalculatePMTRequest) Descriptor() ([]byte, []int) {
	return file_loan_payment_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *CalculatePMTRequest) GetRate() *Decimal {
	if x != nil {
		return x.Rate
	}
	return nil
}

func (x *CalculatePMTRequest) GetNper() int32 {
	if x != nil {
		return x.Nper
	}
	return 0
}

func (x *CalculatePMTRequest) GetPresentValue() *Decimal {
	if x != nil {
		return x.PresentValue
	}
	return nil
}

func (x *CalculatePMTRequest) GetFutureValue() *Decimal {
	if x != nil {
		return x.FutureValue
	}
	return nil
}

func (x *CalculatePMTRequest) GetPaymentTiming() PaymentTiming {
	if x != nil && x.PaymentTiming != nil {
		return *x.PaymentTiming
	}
	return PaymentTiming_PAYMENT_TIMING_UNSPECIFIED
}

type CalculatePMTResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payment       *Decimal               `protobuf:"bytes,1,opt,name=payment,proto3" json:"payment,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculatePMTResponse) Reset() {
	*x = CalculatePMTResponse{}
	mi := &file_loan_payment_calculator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculatePMTResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculatePMTResponse) ProtoMessage() {}

func (x *CalculatePMTResponse) ProtoReflect() protoreflect.Message {
	mi := &file_loan_payment_calculator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculatePMTResponse.ProtoReflect.Descriptor instead.
func (*CalculatePMTResponse) Descriptor() ([]byte, []int) {
	return file_loan_payment_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *CalculatePMTResponse) GetPayment() *Decimal {
	if x != nil {
		return x.Payment
	}
	return nil
}

// Decimal representation as a string to preserve precision
// The value should be a valid decimal number in string format.
// Example: "12345.67"
// It is the responsibility of the client and server to handle parsing and formatting.
type Decimal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Decimal) Reset() {
	*x = Decimal{}
	mi := &file_loan_payment_calculator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Decimal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Decimal) ProtoMessage() {}

func (x *Decimal) ProtoReflect() protoreflect.Message {
	mi := &file_loan_payment_calculator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Decimal.ProtoReflect.Descriptor instead.
func (*Decimal) Descriptor() ([]byte, []int) {
	return file_loan_payment_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *Decimal) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_loan_payment_calculator_proto protoreflect.FileDescriptor

const file_loan_payment_calculator_proto_rawDesc = "" +
	"\n" +
	"\x1dloan_payment_calculator.proto\x12\x1aloan_payment_calculator.v1\x1a\x1cgoogle/api/annotations.proto\"\xf4\x02\n" +
	"\x13CalculatePMTRequest\x127\n" +
	"\x04rate\x18\x01 \x01(\v2#.loan_payment_calculator.v1.DecimalR\x04rate\x12\x12\n" +
	"\x04nper\x18\x02 \x01(\x05R\x04nper\x12H\n" +
	"\rpresent_value\x18\x03 \x01(\v2#.loan_payment_calculator.v1.DecimalR\fpresentValue\x12K\n" +
	"\ffuture_value\x18\x04 \x01(\v2#.loan_payment_calculator.v1.DecimalH\x00R\vfutureValue\x88\x01\x01\x12U\n" +
	"\x0epayment_timing\x18\x05 \x01(\x0e2).loan_payment_calculator.v1.PaymentTimingH\x01R\rpaymentTiming\x88\x01\x01B\x0f\n" +
	"\r_future_valueB\x11\n" +
	"\x0f_payment_timing\"U\n" +
	"\x14CalculatePMTResponse\x12=\n" +
	"\apayment\x18\x01 \x01(\v2#.loan_payment_calculator.v1.DecimalR\apayment\"\x1f\n" +
	"\aDecimal\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*y\n" +
	"\rPaymentTiming\x12\x1e\n" +
	"\x1aPAYMENT_TIMING_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cPAYMENT_TIMING_END_OF_PERIOD\x10\x01\x12&\n" +
	"\"PAYMENT_TIMING_BEGINNING_OF_PERIOD\x10\x022\xb0\x01\n" +
	"\x1cLoanPaymentCalculatorService\x12\x8f\x01\n" +
	"\fCalculatePMT\x12/.loan_payment_calculator.v1.CalculatePMTRequest\x1a0.loan_payment_calculator.v1.CalculatePMTResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/v1/calculate-pmtB7Z5loan_payment_calculator/v1;loan_payment_calculator_v1b\x06proto3"

var (
	file_loan_payment_calculator_proto_rawDescOnce sync.Once
	file_loan_payment_calculator_proto_rawDescData []byte
)

func file_loan_payment_calculator_proto_rawDescGZIP() []byte {
	file_loan_payment_calculator_proto_rawDescOnce.Do(func() {
		file_loan_payment_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_loan_payment_calculator_proto_rawDesc), len(file_loan_payment_calculator_proto_rawDesc)))
	})
	return file_loan_payment_calculator_proto_rawDescData
}

var file_loan_payment_calculator_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_loan_payment_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_loan_payment_calculator_proto_goTypes = []any{
	(PaymentTiming)(0),           // 0: loan_payment_calculator.v1.PaymentTiming
	(*CalculatePMTRequest)(nil),  // 1: loan_payment_calculator.v1.CalculatePMTRequest
	(*CalculatePMTResponse)(nil), // 2: loan_payment_calculator.v1.CalculatePMTResponse
	(*Decimal)(nil),              // 3: loan_payment_calculator.v1.Decimal
}
var file_loan_payment_calculator_proto_depIdxs = []int32{
	3, // 0: loan_payment_calculator.v1.CalculatePMTRequest.rate:type_name -> loan_payment_calculator.v1.Decimal
	3, // 1: loan_payment_calculator.v1.CalculatePMTRequest.present_value:type_name -> loan_payment_calculator.v1.Decimal
	3, // 2: loan_payment_calculator.v1.CalculatePMTRequest.future_value:type_name -> loan_payment_calculator.v1.Decimal
	0, // 3: loan_payment_calculator.v1.CalculatePMTRequest.payment_timing:type_name -> loan_payment_calculator.v1.PaymentTiming
	3, // 4: loan_payment_calculator.v1.CalculatePMTResponse.payment:type_name -> loan_payment_calculator.v1.Decimal
	1, // 5: loan_payment_calculator.v1.LoanPaymentCalculatorService.CalculatePMT:input_type -> loan_payment_calculator.v1.CalculatePMTRequest
	2, // 6: loan_payment_calculator.v1.LoanPaymentCalculatorService.CalculatePMT:output_type -> loan_payment_calculator.v1.CalculatePMTResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_loan_payment_calculator_proto_init() }
func file_loan_payment_calculator_proto_init() {
	if File_loan_payment_calculator_proto != nil {
		return
	}
	file_loan_payment_calculator_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_loan_payment_calculator_proto_rawDesc), len(file_loan_payment_calculator_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_loan_payment_calculator_proto_goTypes,
		DependencyIndexes: file_loan_payment_calculator_proto_depIdxs,
		EnumInfos:         file_loan_payment_calculator_proto_enumTypes,
		MessageInfos:      file_loan_payment_calculator_proto_msgTypes,
	}.Build()
	File_loan_payment_calculator_proto = out.File
	file_loan_payment_calculator_proto_goTypes = nil
	file_loan_payment_calculator_proto_depIdxs = nil
}
