FROM bufbuild/buf:latest

# Install protoc.
RUN apk add --no-cache protobuf-dev

# Update package repositories
RUN apk update

# Install Go from repositories
RUN apk add go

ARG GOPATH=/root/go
ARG PATH=${GOPATH}/bin:/usr/local/go/bin:$PATH
ENV GOPATH=${GOPATH}
ENV PATH=${PATH}

RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@latest
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@latest

# Verify installations.
RUN buf --version && \
    protoc --version

# Set working directory.
WORKDIR /workspace
